from app.model.user_table import UserTable
from app.model.wallet_table import WalletTable
from app.model.settings_table import SettingsTable
from app.model.transaction_table import TransactionTable
from app.model.otp_table import OTPTable
from app.model.notification_table import NotificationTable
from app.model.sessions_table import SessionTable
from app.model.bill_providers_table import BillProviderTable
from app.model.mobile_operator_table import MobileOperatorTable
from app.model.country_table import CountryTable
from app.model.password_reset_table import ResetPasswordTable
from app.model.donation_table import DonationTable
from app.model.admin_table import AdminTable
from app.model.admin_session_table import AdminSessionTable
from app.model.bank_table import BankTable
from app.model.delete_user_table import DeletedUserTable
from app.model.dev_table import DevTable