"""initial migration

Revision ID: 17e7d69603d8
Revises: 
Create Date: 2026-05-12 10:43:27.722421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e7d69603d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_list', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_admin_list_admin_id'), table_name='admin_list')
    op.create_index(op.f('ix_admin_list_id'), 'admin_list', ['id'], unique=False)
    op.create_unique_constraint(None, 'admin_list', ['admin_id'])
    op.alter_column('admin_sessions', 'admin_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('admin_sessions', 'id')
    op.add_column('bank_list', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    op.create_index(op.f('ix_bank_list_id'), 'bank_list', ['id'], unique=False)
    op.create_unique_constraint(None, 'bank_list', ['bank_id'])
    op.add_column('bill_providers', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    op.alter_column('bill_providers', 'company_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_bill_providers_id'), 'bill_providers', ['id'], unique=False)
    op.create_unique_constraint(None, 'bill_providers', ['company_id'])
    op.add_column('country_list', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    op.create_index(op.f('ix_country_list_id'), 'country_list', ['id'], unique=False)
    op.create_unique_constraint(None, 'country_list', ['counrty_id'])
    op.create_unique_constraint(None, 'country_list', ['counrty_code'])
    op.create_index(op.f('ix_deleted_user_id'), 'deleted_user', ['id'], unique=False)
    op.drop_column('user_settings', 'totp_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('totp_secret', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_deleted_user_id'), table_name='deleted_user')
    op.drop_constraint(None, 'country_list', type_='unique')
    op.drop_constraint(None, 'country_list', type_='unique')
    op.drop_index(op.f('ix_country_list_id'), table_name='country_list')
    op.drop_column('country_list', 'id')
    op.drop_constraint(None, 'bill_providers', type_='unique')
    op.drop_index(op.f('ix_bill_providers_id'), table_name='bill_providers')
    op.alter_column('bill_providers', 'company_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('bill_providers', 'id')
    op.drop_constraint(None, 'bank_list', type_='unique')
    op.drop_index(op.f('ix_bank_list_id'), table_name='bank_list')
    op.drop_column('bank_list', 'id')
    op.add_column('admin_sessions', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('admin_sessions', 'admin_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'admin_list', type_='unique')
    op.drop_index(op.f('ix_admin_list_id'), table_name='admin_list')
    op.create_index(op.f('ix_admin_list_admin_id'), 'admin_list', ['admin_id'], unique=1)
    op.alter_column('admin_list', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
