
class String:
    SMS_URL = "http://10.239.102.32:8000/send"
    DEMO_PROFILE_IMAGE_URL = "https://res.cloudinary.com/dgh76k5vn/image/upload/v1741357531/new_user_profile_atwuhv.png"

    # detalse message
    USER_NOT_FOUND = "User Not Found"
    ADMIN_NOT_FOUND = "Admin Not Found"
    ADMIN_NOT_LOGIN = "Admin Not Login"
    INVALID_PASSWORD = "Invalid Password"
    INVALID_EMAIL_ADDRESS = "Invalid Email Address"
    INVALID_PHONE_NUMBER = "Invalid Phone Number"
    WALLET_NOT_FOUND = "Wallet Not Found"
    INVALID_TOKEN = "Invalid Token"
    ACCOUNT_LOCKED = "Account Locked"
    SESSION_NOT_FOUND = "Session Not Found"
    OTP_NOT_VERIFIED = "OTP Not Verified"
    SETTINGS_NOT_FOUND = "Settings Not Found"
    INVALID_TOKEN_TYPE = "Invalid Token Type"
    USER_NOT_LOGIN = "User Not Login"
    INVALID_OR_EXPIRED_TOKEN = "Invalid or Expired Token"
    SERVER_ERROR = "Internal Server Error"
    COUNTRIES_ALREADY_EXISTS = "Country Already Exists"
    INSUFFICIENT_BALANCE = "Insufficient Balance"
    EMAIL_OR_PHONE_REQUIRED  = "Email or Phone is Required"
    LOGOUT_SUCCESSFUL = "Logout Successful"
    PASSWORD_RESET_NOT_FOUND = "Password Reset Not Found"
    PASSWORD_RESET_ALREADY_SENT = "Password Reset Already Sent"
    INVALID_OTP = "Invalid OTP"
    OTP_NOT_FOUND = "OTP Not Found"
    TIME_LIMET_EXPAIRE = "Time Expaire. Please Try Again."
    NO_COUNTRY_FOUND = "No Country Found"
    USER_ALRADY_EXISTS = "User Already Exists"
    PASSWORD_RESET_SUCCESSFUL = "Password Reset Successful"
    PASSWORD_NOT_SET = "Password Not Set"
    VERIFY_KYC_FIRST = "Verify KYC First"
    SYSTEM_USER_ID = "PocketPay"
    
    